version: 2

sources:
  - name: external_parquet
    meta:
      external_location: "D:\\git\\dbt-duckdb-demo\\external\\in\\{name}.parquet"
    tables:
      - name: mtcars
        description: 'mtcars dataset from R as parquet'

models:
  - name: mtcars_gear_count
    description: 'testing external writing!'

  - name: mtcars_python_test
    description: 'my first python model'
