version: 2

sources:
  - name: external_parquet
    meta:
      external_location: "D:\\git\\dbt-duckdb-demo\\external\\in\\{name}.parquet"
    tables:
      - name: mtcars
        description: 'mtcars dataset from R as parquet'
        columns:
          - name: mpg
            type: numeric
            description: 'miles per gallon'
          - name: cyl
            type: numeric
            description: 'number of cylinders in engine'
          - name: wt
            type: numeric
            description: 'weight of car in tons'
          - name: gears
            type: numeric
            description: 'number of gears in drive'
  - name: external_csv
    meta:
      external_location: "D:\\git\\dbt-duckdb-demo\\external\\in\\{name}.csv"
    tables:
      - name: insurance3r2
        description: 'Sample insurance calim prediction dataset from kaggle: https://www.kaggle.com/datasets/easonlai/sample-insurance-claim-prediction-dataset?resource=download'
        columns:
          - name: age
            type: numeric
            description: 'age of policyholder'
          - name: sex
            type: numeric
            description: 'gender of policy holder (female=0, male=1)'
          - name: bmi
            type: numeric
            description: 'Body mass index, providing an understanding of body, weights that are relatively high or low relative to height, objective index of body weight (kg / m ^ 2) using the ratio of height to weight, ideally 18.5 to 25'
          - name: steps
            type: numeric
            description: 'average walking steps per day of policyholder'
          - name: children
            type: numeric
            description: 'number of children / dependents of policyholder'
          - name: smoker
            type: numeric
            description: 'smoking state of policyholder (non-smoke=0;smoker=1)'
          - name: region
            type: numeric
            description: 'the residential area of policyholder in the US (northeast=0, northwest=1, southeast=2, southwest=3)'
          - name: charges
            type: numeric
            description: 'individual medical costs billed by health insurance'
          - name: insuranceclaim
            type: numeric
            description: 'yes=1, no=0'
