version: 2

sources:
  - name: external_parquet
    meta:
      external_location: "D:\\git\\dbt-duckdb-demo\\external\\in\\{name}.parquet"
    tables:
      - name: mtcars
        description: 'mtcars dataset from R as parquet'
