version: 2

sources:
  - name: external_parquet
    meta:
      external_location: "D:\\git\\dbt-duckdb-demo\\external\\in\\{name}.parquet"
    tables:
      - name: mtcars
        description: 'mtcars dataset from R as parquet'
        columns:
          - name: mpg
            type: numeric
            description: 'miles per gallon'
          - name: cyl
            type: numeric
            description: 'number of cylinders in engine'
          - name: wt
            type: numeric
            description: 'weight of car in tons'
          - name: gears
            type: numeric
            description: 'number of gears in drive'
  - name: external_csv
    meta:
      external_location: "D:\\git\\dbt-duckdb-demo\\external\\in\\{name}.csv"
    tables:
      - name: insurance3r2
        description: 'Sample insurance calim prediction dataset from kaggle: https://www.kaggle.com/datasets/easonlai/sample-insurance-claim-prediction-dataset?resource=download'
        columns:
          - name: age
            type: numeric
            description: '{{ doc("insurance_details_age") }}'
          - name: sex
            type: numeric
            description: '{{ doc("insurance_details_sex") }}'
          - name: bmi
            type: numeric
            description: '{{ doc("insurance_details_bmi") }}'
          - name: steps
            type: numeric
            description: '{{ doc("insurance_details_steps") }}'
          - name: children
            type: numeric
            description: '{{ doc("insurance_details_children") }}'
          - name: smoker
            type: numeric
            description: '{{ doc("insurance_details_smoker") }}'
          - name: region
            type: numeric
            description: '{{ doc("insurance_details_region") }}'
          - name: charges
            type: numeric
            description: '{{ doc("insurance_details_charges") }}'
          - name: insuranceclaim
            type: numeric
            description: '{{ doc("insurance_details_insuranceclaim") }}'
